<?php

namespace App\DecoratorPattern\Repository;

use App\DecoratorPattern\Repository\UserDecoratedRepository;
use Illuminate\Support\Facades\Cache;

class CacheUserRepositoryDecorated extends UserDecoratedRepository
{
    //         return parent::getUserById($id); // TODO: Change the autogenerated stub
     public function getUserById($id)
     {
         $key='user_'.$id;
         if (!Cache::has($key)) {
             $user=parent::getUserById($id);
             Cache::put($key, $user, 60);

         }
         $user = Cache::get($key);
         return $user;

     }
}
